config/routes.rb
Rails.application.routes.draw do

  get '/products', to: 'products#index'

  get '/products/new', to: 'products#new'
  post '/products', to: 'products#create'

  get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch '/products/:id', to: 'products#update'
    
  get '/products/:id', to: 'products#show', as: 'product'

  delete '/products/:id', to: 'products#destroy'
  
  get '/songs/:id', to: 'songs#show'
  get '/songs' => 'songs#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  CATEGORIES = ['Apparel', 'Kitchen', 'Entertainment', 'Software']
  
  # A Product MUST have a name
  validates :name, presence: true
  # A Product name MUST be at least 3 characters.
  validates :name, length: { minimum: 3}
  # A Product name MUST be unique
  validates :name, uniqueness: true
  # The price MUST be a number
  # validates :price, numericality: true
  # The price MUST be of the format that 'matches' the regular expression, regex.
  validates :price, format: { :with => /\A\d+(\.\d{2})?\z/, message: 'Must be a zero or more digits, a period, followed by two digits' }
  # A category must be one the above
  validates :category, inclusion: { in: CATEGORIES }
  
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Run this before every action
  before_filter :set_title

  private 

  def set_title
    @title = self.class.name.split('Controller').first
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  def index
    # Get a collection of all the products 
    # in the DB.
    # Behaves like an Array. 
    # SELECT * FROM products;
    @products = Product.all

    # By Default render the view with the 
    # same name as the action.
    # render :index
  end

  # GET /products/:id
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.create(product_params)
    
    if @product.valid?
      # It saved, so lets see this new product
      redirect_to @product, notice: 'You created a new product'
    else
      # No worky, try again, show me the form you.
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: "You have updated the #{@product.name}"
    else
      # No worky, try again, show me the form you.
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: "You have deleted the product"
  end
  
  private

  def set_title
    @title = "Awesome Products!"
  end

  def product_params
    params.require(:product).permit([:name, :description, :price, :category])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  # GET /songs
  def index
    @songs = Song.all
  end

  # GET /songs/:id
  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Honest Tom's Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='container'>
    <div id='header'>
      <h2> Honest Tom's <%= @title %></h2> 
    </div>
    <div id='contents'>
      <%= yield %>
    </div>
  </div>
  <footer>
    <ul>About
      <li> Host <a href='https://generalassemb.ly/instructors/tom-dyer/1717'>Tom</a></li>
    </ul>
  </footer>
</body>
</html>

app/views/products/_form.html.erb
<!-- product is local variable of this partial -->
<%= form_for product do |f| %>
  <%= f.label :name %> <br> 
  <%= f.text_field :name %> 
  <br> 
  <%= f.label :description %> <br> 
  <%= f.text_area :description %> 
  <br> 
  <%= f.label :price %> <br> 
  <%= f.text_field :price %> 
  <br> 
  <%= f.label :category %> <br> 
  <%= f.text_field :category %> 
  <br> 
  <%= f.submit %> 
<% end %>

app/views/products/_product.html.erb
   <li> Name: <%= product.name %></li>
   <li> Description: <%= product.description %></li>
   <li> Price: <%= product.price %></li>
   <li> Category: <%= product.category %></li>
   <li> <%= link_to 'Show', product_path(product) %></li>
   <li> <%= link_to 'Edit', edit_product_path(product) %></li>
   <li> <%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></li>

app/views/products/_product_layout.html.erb
<ul>
<%= yield %>
</ul>
<br>
<hr>

app/views/products/edit.html.erb
<h3>Update Product <%=@product.name %><h3>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this
      post from being updated:</h2>
 
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<!-- Pass the instance variable, @product, to the partial -->
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<ul>
<%= render partial: "product", collection: @products, layout: 'product_layout' %>
</ul>
<h3><%= link_to 'Create a new Product', products_new_path %></h3>

app/views/products/new.html.erb
<h3>Update Product <%= @product.name %><h3>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this
      post from being saved:</h2>
 
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<!-- Pass the instance variable, @product, to the partial -->
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h4> Product <%= @product.name %></h4>
<p> Price <%= @product.price %></p>
<p> Description <%= @product.description %></p>
<p> Category <%= @product.category %></p>
<%= link_to 'Update', edit_product_path(@product) %> 

app/views/songs/index.html.erb
<ul>
<% @songs.each do |song| %>
  <ul>
    <li>Title: <%= song.title %></li>
    <li>Genre: <%= song.genre %></li>
    <li>Price: <%= song.price %></li>
  </ul>
  <br/>
<% end %>
</ul>

app/views/songs/show.html.erb
<h4>Title: <%= @song.title %></h4>
<p>Genre <%=@song.genre%></p>
<p>Price <%=@song.price%></p>